site_name: Communities of Practice
repo_url: https://github.com/acodeninja/community-of-practice-template
repo_name: acodeninja/community-of-practice-template
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit

plugins:
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - abbr
  - toc:
      permalink: true
      title: On this page
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
