site_name: Communities of Practice
repo_url: https://github.com/acodeninja/community-of-practice-template
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.action.edit

plugins:
  - kroki
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
